= Проект BugTracker бот для телеграм

== TODO

. Reminders
    .. При удалении Reminder нужно убирать его из таблички
    .. Страничка вывода Reminders
    .. Страничка редактирования Reminder
        ... Ввод даты относительно текущего времени (через день, в следующую пятницу и тд)
. Определиться с inline keyboard




== Класс Task


=== Правила, как могут переходить статусы в задачах

- Нельзя переходить в тот-же статус, что и сейчас.
- Нельзя перепрыгивать через Done: из активного сразу в архив и наоборот.

=== Правила, задачи с какими статусами можно добавлять

К задаче можно добавить статус с таким-же или более высоким статусом:
- к активной - любую
- к выполненой - выполненую или архивную
- к архивной - только другую архивную

=== TODO

. Сделать поиск по ID задачи



== Интерфейс Datastore

=== Описание интерфейса

У нас есть один метод - get, который принимает лист аргументов (?) и возвращает строку.

Какие именно данные нам нужно получать:

- JSON с списком задач по имени пользователя (можно еще разбить на задачи от корня)
- Элементы конфигурации
- И тд, всякое такое.

Как это работает:

Мы формируем запрос в БД (файлы, redis, всё, что угодно) в виде `"arg1:arg2:arg3:...:argn"`, и делаем запрос к базе (ключ - значение).




== Интерфейс бота



.Список от корня, команда */list*
----
*Tasks:*
Задача 1 /list1
Задача 2 /list2

Buttons:
/prev /new /next
----

.Список подзадач, команда /list1
----
*Задача 1* /detail1
[v] Придумать тему /done11 /list11
[ ] Придумать ещё что-то /done12 /list12

Buttons:
/prev /new1 /next
----

.Детали задачи, команда */detail123*
----
*сделать задачу* /edit1
Subject: сделать задачу
Description: сделать какую-то задачу.
State: active /done
Remind: 12 августа 8:00

Buttons:
/edit1 /done1 /reminder1
----

.Список напоминаний, команда /reminders
----
*Reminders:*
Задача 1 - 12 августа 8:00 /reminder1
Задача 2 - 15 августа 9:00 /reminder2
----

.Поиск задачи по названию, команда /find
----
*Find:*
Задача 1 /list1
Задача 2 /list2
----



=== Список доступных команд

|====
| Команда           | Параметры
| `/list[currentID]`       | Если без параметров - список задач от корня. Иначе список подзадач задачи с номером currentID
| `/new[currentID] subj`   | Новая задача (или подзадача). Может быть сразу задана тема
| `/detail{currentID}`     | Подробный вывод задачи с номером currentID
| `/done{currentID}`       | Установить статус для задачи в выполнено
| `/archive{currentID}`    | Установить статус для задачи в архивировано
| `/edit{currentID}`       | Переход в режим редактирования задачи
|  |
|====


=== Подумаем над таблицей состояний


.Состояния
====
*Какие есть вообще состояния (собственно экраны):*

|====
| Состояние                                     | Класс

| Просмотр подзадач конкретной задачи или корня | ListState
| Просмотр деталей задачи                       | DetailState
| Редактирование задачи                         | EditState
| Создание новой задачи (?)                     | NewTaskState
| Редактирование напоминания                    | RemindState
| Просмотр результатов поиска                   | FindState
|====
====

.Действия
====
*Какие есть действия (в скобках параметры):*

|====
| Действие                                          | Команда              | Откуда может быть вызвано

| Переход к списку задач                            | /main                | Из любого
| Переход к списку подзадач задачи                  | /list{id}            |
| Переход к деталям задачи                          | /detail{id}          |
| Редактировать задачу                              | /edit{id}            |
| Создать новую задачу                              | /new{id}             |
| Открыть редактирование напоминания задачи         | /reminder{id}        |
| Переход к списку напоминаний                      | /reminders           |
| Пометить задачу сделаной                          | /done{id}            |
| Пометить задачу активной                          | /undone{id}          |
| Архивировать задачу                               | /archive{id}         |
| Разархивировать задачу                            | /unarchive{id}       |

| Выполнить поиск (строка для поиска)               | /find {text}         |
| Показывать или скрывать выполненые задачи         | /showDone /hideDone  |
|====
====

.Статус
====
*Что именно нам нужно будет хранить*

. Наше текущее положение в списке задач (текущая задача или корень)
. Показывать или нет выполненые задачи
====


[IMPORTANT]
====
Подумать про это:

* Как и когда будут отображаться архивные задачи?
====

== Что делать с сейвером?

. У нас есть переменная с функцией saver, которая должна сохранять данные на диск для определенного пользователя.
. При загрузке из JSON эта переменная равна нулю.

Что делать?

Варианты:

. Найти корень, где эта функция установлена.
+
Минус данного решения в том, что тогда нужно будет пробрасывать родителя в потомков.
. Автоматически устанавливать эту функцию при загрузке из JSON
. Устанавливать для данной задачи и для всех подзадач.


== Как собирать и выводить напоминания?

Проблемы:

Нам нужно как-то собирать список дат, когда выводить напоминания. Этот список где-то должен обновляться.

Варианты:

*Собирать список, периодически пробегая по всем юзерам.*

Плюсы:

* Данные о напоминаниях хранятся в одном месте. Нет возможности сломать целостность данных.

Минусы:

* Можно пропустить пользователя.
* При большом количестве пользователей это будет очень затратный процесс.


*Добавлять запись в список при изменении/добавлении напоминания.*

Плюсы:

* Нет необходимости пробегать по всем пользователям. Данные собираются "автоматически".

Минусы:

* Усложняется операция сохранения при изменении данных.


Как же собирать данные?

При каждой записи нужно дополнительно сохранять



== Парсинг естественного текста

. Когда?
    .. в...
        ... в 7 часов в 27 мая
        ... 27 мая в 7 часов
        ... в следующую пятницу в обед
        ... в первую пянницу месяца
        ... в половине 12
        ... в 15 минут первого
        ... в без 10 минут два
    .. через...
        ... через 10 минут
        ... через три дня
        ... через день в обед
    .. завтра
        ... сегодня
            .... сегодня в обед
            .... сегодня через 10 минут
        ... завтра
        ... послезавтра





Итак, у нас есть части:

. в
    .. обед
    .. 7 часов 30 минут
    .. 7:30
    .. половине восьмого
    .. без двадцати восемь
    .. двадцать минут восьмого
    .. следующую пятницу
. когда?
    .. 27 июля
    .. утром / вечером
    .. перед сном
    .. завтра / послезавтра
. через
    .. 10 минут
    .. пол часа
    .. три дня
    .. три недели
    .. три месяца
    .. год


сделать дело завтра в обед
сделать дело завтра в 7 часов 30 минут
сделать дело 27 июля в 7:30
сделать дело в пол восьмого завтра
сделать дело в следующую пятницу в обед


. Данные про дату
    .. 27 июля
    .. в следующую пятницу
    .. в пятницу
    .. завтра
    .. через день
    .. через неделю
    .. через год
. Данные про время
    .. в семь часов
    .. в семь
    .. в 7:30
    .. утром, вечером, в обед, перед сном
    .. в половине восьмого
    .. в двадцать минут восьмого
    .. в без двадцати восемь
    .. без двадцати восемь
    .. через 10 минут


Порядок разбора:

. Перевести всё что можно в цифру
    .. Все числа, записаные текстом, перевести в цифры
    .. Найти все месяцы, дни недели и тд.
    .. Найти понятия обед, вечер, утро, и перевести их в цифры.

    .. Понятия "следующий" перевести в "число +1"
    .. "через" + ("число x")? => "число x+2" (???????)

. Объединить рядом стоящие цифры
. Распарсить дату
    .. Число + месяц => дата
    .. на "число" неделе (в "день недели (или понедельник)")? => дата
. Распарсить время
    .. Фраза: цифра, ("часа")? "утра", "дня", "вечера", "ночи" => время
    .. Фраза: ("в")? + "без" + цифра + ("минут")? => время
    .. Фраза: "в половине" => время
    .. Объеденить рядом стоящее время
    .. Объеденить время + цифра в время
. Объединить стоящие рядом время и дату. Остальной текст - в текст.





[source, text]
-------------------------------------------------------------------------------
{выключить} {воду} {через} {десять} {минут}
{выключить} {воду} {keyword через} {number 10} {keyword минут}
{выключить} {воду} {time +0:10}
{выключить} {воду} {date_time 26.07 15:30}
{text выключить воду} {date_time 26.07 15:30}
-------------------------------------------------------------------------------


[source, text]
-------------------------------------------------------------------------------
{однажды} {в} {студёную} {зимнюю} {пору} {выучить} {в} {воскресенье}
{однажды} {keyword в} {студёную} {зимнюю} {пору} {выучить} {keyword в} {day_of_week воскресенье}
{однажды} {keyword в} {студёную} {зимнюю} {пору} {выучить} {date 31.07}
{однажды} {keyword в} {студёную} {зимнюю} {пору} {выучить} {date_time 31.07 8:00}
{text однажды в студёную зимнюю пору выучить} {date_time 31.07 8:00}
-------------------------------------------------------------------------------



[source, text]
-------------------------------------------------------------------------------
{напомни} {мне} {через} {две} {недели} {в} {среду} {купить} {хлеба} {в} {половине} {третьего}

    Заменяю все числительные, дни недели, месяцы и тд.
    Нахожу ключевые слова, выделяю их.

{напомни} {мне} {keyword через} {number 2} {keyword недели} {keyword в} {day_of_week среда} {купить} {хлеба} {keyword в} {keyword половине} {number 3}

    Обрабатываю соединения {через} + {number} => {number +x}

{напомни} {мне} {number +2} {keyword недели} {keyword в} {day_of_week среда} {купить} {хлеба} {keyword в} {keyword половине} {number 3}

    Дата:
    {number +2} {недели} => {day +14}

{напомни} {мне} {day +14} {keyword в} {day_of_week среда} {купить} {хлеба} {keyword в} {keyword половине} {number 3}

    {в} {day_of_week среда} => {date 27.07}

{напомни} {мне} {day +14} {date 27.07} {купить} {хлеба} {keyword в} {keyword половине} {number 3}

    {day +14} {date 27.07} => {date 10.08}

{напомни} {мне} {date 10.08} {купить} {хлеба} {keyword в} {keyword половине} {number 3}

    Всё. Дата в окружении обычных слов.
    Ищу время.
    {keyword половине} => {time -0:30}

{напомни} {мне} {date 10.08} {купить} {хлеба} {keyword в} {time -0:30} {number 3}

    ({keyword в})? {time -0:30} {number 3} => {time 2:30}

{напомни} {мне} {date 10.08} {купить} {хлеба} {time 2:30}

    Всё, время в окружении обычного текста.
    Объединяем дату и время.
    {date 10.08} + {time 2:30} => {date_time 10.08 2:30}

{напомни} {мне} {купить} {хлеба} {date_time 10.08 2:30}

    Собираем текст

{text напомни мне купить хлеба} {date_time 10.08 2:30}
-------------------------------------------------------------------------------

[source, text]
-------------------------------------------------------------------------------
{на} {следующей} {неделе} {в} {понедельник} {утром} {сделать} {дело}

Заменяю все числительные, дни недели, месяцы и тд.
Нахожу ключевые слова, выделяю их.

{keyword на} {keyword следующей} {keyword неделе} {keyword в} {day_of_week понедельник} {time 8:00} {сделать} {дело}

Ищу дату.
{keyword на} {keyword следующей} => {number +1}

{number +1} {keyword неделе} {keyword в} {day_of_week понедельник} {time 8:00} {сделать} {дело}

{number +1} {keyword неделе} => {day +7}
{keyword в} {day_of_week понедельник} => {date 24.07}

{day +7} {date 24.07} {time 8:00} {сделать} {дело}

{day +7} {date 24.07} => {date 31.07}

{date 31.07} {time 8:00} {сделать} {дело}

{date 31.07} {time 8:00} => {date_time 31.07 8:00}

{date_time 31.07 8:00} {сделать} {дело}

{date_time 31.07 8:00} {text сделать дело}
-------------------------------------------------------------------------------


[source, text]
-------------------------------------------------------------------------------
{text напомни мне через две недели в среду купить хлеба в половине третьего}
Нахожу все числительные. Заменяю.

{text напомни мне через} {number 2} {text недели в} {day_of_week среда} {text купить хлеба в половине} {number 3}
Через + число => число

{text напомни мне через} {number 2} {text недели в} {day_of_week среда} {text купить хлеба в половине} {number 3}


-------------------------------------------------------------------------------

[source, text]
-------------------------------------------------------------------------------
на следующей неделе в понедельник утром сделать дело
на {number +1} неделе в {day_of_week понедельник} {time 8:00} сделать дело
{date 29 июль} {time 8:00} сделать дело
{date_time 29 июль 8:00} {text сделать дело}
-------------------------------------------------------------------------------

[source, text]
-------------------------------------------------------------------------------
сделать дело в пол восьмого завтра
сделать дело в пол {8} {date today+1}
сделать дело {time 7:30} {date today+1}
сделать дело {date 27:07 7:30}
{text сделать дело} {date 27:07 7:30}
-------------------------------------------------------------------------------

[source, text]
-------------------------------------------------------------------------------
сделать дело двадцать седьмого января в без двадцати трех минут восемь вечера
сделать дело {number 20} {number 7} {month январь} в без {number 20} {number 3} минут {number 8} вечера
сделать дело {number 27} {month январь} в без {number 23} минут {number 8} вечера
сделать дело {date 27 январь} в без {number 23} минут {number 8} вечера
сделать дело {date 27 январь} в без {number 23} минут {time 20:00}
сделать дело {date 27 январь} {time -0:23} {time 20:00}
сделать дело {date 27 январь} {time 19:37}
{text сделать дело} {date_time 27 январь 19:37}
-------------------------------------------------------------------------------





[cols="",opts="autowidth"]
|===
|на             | в

|понедельник    |
|вторник        |
|среда          | среду
|четверг        |
|пятница        | пятницу
|суббота        | субботу
|воскресенье    |
|===

[cols="",opts="autowidth"]
|===
| час           | числа             | без           | в

| один          | первого           | одной         | одну
| два           | второго           | двух          | две
| три           | третьего          | трех          |
| четыре        | четвертого        | четырех       |
| пять          | пятого            | пяти          |
| шесть         | шестого           | шести         |
| семь          | седьмого          | семи          |
| восемь        | восьмого          | восьми        |
| девять        | девятого          | девяти        |
| десять        | десятого          | десяти        |
| одиннадцать   | одиннадцатого     | одиннадцати   |
| двенадцать    | двенадцатого      | двенадцати    |
| тринадцать    | тринадцатого      | тренадцати    |
| четырнадцать  | четырнадцатого    | черырнадцати  |
| пятнадцать    | пятнадцатого      | пятнадцати    |
| шестнадцать   | шестнадцатого     | шестьнадцати  |
| семьнадцать   | семьнадцатого     | семьнадцати   |
| восемьнадцать | восемьнадцатого   | восемьнадцати |
| девятьнадцать | девятьнадцатого   | девятьнадцати |
| двадцать      | двадцатого        | двадцати      |
| тридцать      |                   | тридцати      |
| сорок         |                   | сорока        |
| пятьдесят     |                   | пятидесяти    |
|===

[cols="",opts="autowidth"]
|===
| на        | начало

| январь    | января
| февраль   | февраля
| март      | марта
| апрель    | апреля
| май       | мая
| июнь      | июня
| июль      | июля
| август    | августа
| сентябрь  | сентября
| октябрь   | октября
| ноябрь    | ноября
| декабрь   | декабря
|===

[cols="",opts="autowidth"]
|===
| 1         | 3         | 5

| секунда   | секунды   | секунд
| минута    | минуты    | минут
| час       | часа      | часов
| день      | дня       | дней
| неделя    | недели    | недель
| месяц     | месяца    | месяцев
| год       | года      | лет
|===


[cols="",opts="autowidth"]
|===
| когда     | в 9

| утром     | утра
| днем      | дня
| вечером   | вечера
| ночью     | ночи
| в обед    |
|===



[cols="",opts="autowidth"]
|===

| следующий     | следующем     | следующего
| через         |               |
| в             |               |
| без           |               |
| завтра        |               |
| послезавтра   |               |
| половина      | в половине    |
| четверть      | без четверти  |
|===




== Переделаем работу с данными.

У нас есть следующие объекты:

. Задача (`Task`)
. Хранилище данных (`Datastore`)
. Пользовательская сессия (`UserSession`)

Соответственно в Datasore должны храниться Task для определенного пользователя UserSession
Создаём Datastore
Создаём UserSession
Мы работаем только с UserSession



Итак. У Task есть специальный метод notify, в который будет педедаваться значение, что именно поменялось.
Для этого у нас будет специальный Enum, с списком значений.

Далее, это метод позволяет сохранить измененные значения в базе.















